名称: 刷步数

开启:

→ 每天9:00运行
:

:
构建:
运行于: ubuntu-latest
超时分钟: 60
步骤:
      - 名称: 检出代码
使用: actions/checkout@v5

令牌: ${{ secrets.PAT }} #此处PAT需要申请，教程详见：README
     - 
: |
          sudo -E apt-get -qq update
          sudo -E apt-get install zsh -y
          
      - name: 初始化Python
        uses: actions/setup-python@v6
与:
          python-version: "3.10"
          
      - name: 开始
        env:
            CONFIG: ${{ secrets.CONFIG }}
            AES_KEY: ${{ secrets.AES_KEY }}
运行: |
          pip3 install requests pytz pycryptodome
          python3 main.py

      - name: persist tokens
运行: |
          git config user.name github-actions
          git config user.email github-actions@users.noreply.github.com
          git add .
          git commit -m "persist tokens trigger by ${{ github.event_name }}"
          git push origin master
